### ISSUE TITLE
Unsubscribe Event

### ISSUE THREAD

**Issue by xkalf** [afedotov/gan-web-bluetooth#1]
i want to saving connection between pages but its getting events twice how to unsubscribe events?

**Comment by afedotov** [comment]
Your question is related to RxJS. Just learn how to use it.
The `subscribe()` method called on `events$` observable return [Subscription](https://rxjs.dev/guide/subscription) object which has `unsubscribe()` method. Use these resources to learn:

 - https://rxjs.dev/guide/overview
 - https://www.learnrxjs.io/

**Comment by xkalf** [comment]
typescript gets this error 
`ts: Property 'unsubscribe' does not exist on type 'Observable<GanTimerEvent>'. Did you mean 'subscribe'? [2551]`

if i ignore error and switch page and back 
`gan-web-bluetooth.js?v=80112bf3:1032 Uncaught ObjectUnsubscribedErrorImpl {stack: 'Error\n    at _super (http://localhost:5173/node_mo…ite/deps/gan-web-bluetooth.js?v=80112bf3:2501:18)', name: 'ObjectUnsubscribedError', message: 'object unsubscribed'}`

this error

**Comment by afedotov** [comment]
Read the manual carefully. You calling `unsubscribe()` on `Observable`, but should call it on `Subscription`. See how subscription is handled in CubeDesk inside React component: https://github.com/kash/cubedesk/blob/main/client/components/timer/time_display/gantimer/GanTimer.tsx

**Comment by xkalf** [comment]
Problem solved tnx a lot

**Comment by xkalf** [comment]
Propblem solves tnx a lot.
